config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#top_page'

  resources :users do
    member do
      get 'edit_user_info'
      patch 'update_user_info'
    end
  end

  resources :image_videos

  scope :api, { format: 'json' } do
    resources :image_videos do
      get :search, on: :collection
    end
  end

  resources :favorites

  get '/users' => redirect("users/sign_in")
  get '/users/password' => redirect("users/password/new")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image_video.rb
class ImageVideo < ApplicationRecord
  has_many :users, through: :favorites
  has_many :favorites
end

app/controllers/image_videos_controller.rb
class ImageVideosController < ApplicationController
  before_action :set_one_month, only: [:index, :show]

  def index
    @image_videos = ImageVideo.paginate(page: params[:page]).order(:id)
    @users = User.paginate(page: params[:page]).order(:id)
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
  end

  def show
    @image_videos = ImageVideo.paginate(page: params[:page]).order(:id)
  end

  def search
    @q = ImageVideo.ransack(search_params)
    @staffs = @q.result(distinct: true)
  end

  private

  def search_params
    params.require(:q).permit(:photograph_day_on, :title)
  end
end

app/helpers/image_videos_helper.rb
module ImageVideosHelper
end

app/views/image_videos/index.html.erb
<div class="main-container-student-impression">
  <h1 class="label-student-impression"><b>スクール生感想内容検索</b></h1>
    <div class="col-md-3 col-md-offset-8">
      <%= form_with(model: @user, method: :get, local: true) do |f| %>
        <%= f.label :search, "スクール生検索" %>
        <div style="display: inline-flex">
          <%= f.text_field :name, class: "form-control", placeholder: "キーワードを入力" %>
          <%= f.submit "検索", class: "btn btn-md btn-primary btn-name-search" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-6 col-md-6" style="margin-left: 380px; margin-top: 10px;">
        <% @users.each do |user| %>
        <%= will_paginate %>
          <% if @users.count > 0 %>
            <table class="table table-bordered table-condensed table-hover">
              <thead style="color: blue;">
                <tr>
                  <th style="text-align: center;">ID</th>
                  <th style="text-align: center;">名前</th>
                  <th style="text-align: center;">使用サーフボード</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= link_to user.name, image_video_path(user.id) %></td>
                  <td><%= user.using_surfboard %></td>
                </tr>
              </tbody>
            </table>
          <% else %>
            <h3 class="center">スクール生が存在しません。</h3>
          <% end %>
          <%= will_paginate %>
        <% end %>
      </div>
    </div>
</div>

app/views/image_videos/show.html.erb
<div id="el-index">
  <h1>staffs</h1>
  <div class="search-form-static">
  <div class="el-form" ref="form" :model="query" label-width="120px">
    <el-form-item label="名前">
      <el-input v-model="query.name_cont" placeholder="input name"></el-input>
    </el-form-item>
    <el-form-item label="年齢">
      <el-col :span="11">
        <el-input-number v-model="query.age_gteq" :min="0" :max="150"></el-input-number>
      </el-col>
      <el-col class="line" :span="2">-</el-col>
      <el-col :span="11">
        <el-input-number v-model="query.age_lteq" :min="0" :max="150"></el-input-number>
      </el-col>
    </el-form-item>
    <el-form-item label="入社日">
      <el-col :span="11">
        <el-date-picker
          v-model="query.joined_on_gteq"
          type="date"
          placeholder="日時を選択してください">
        </el-date-picker>
      </el-col>
      <el-col class="line" :span="2">-</el-col>
      <el-col :span="11">
        <el-date-picker
          v-model="query.joined_on_lteq"
          type="date"
          placeholder="日時を選択してください">
        </el-date-picker>
      </el-col>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="search">search</el-button>
    </el-form-item>
  </div>
  </div>
  <el-table
    :data="staffs"
    height="400"
    stripe
    style="width: 100%">
    <el-table-column
      prop="name"
      sortable
      label="名前"
      width="180">
    </el-table-column>
    <el-table-column
      prop="age"
      sortable
      label="年齢"
      width="180">
    </el-table-column>
    <el-table-column
      prop="joined_on"
      sortable
      label="入社日">
    </el-table-column>
  </el-table>
</div>

<div class="main-container-student-impression_contents">
<h1 class="label-student-impression"><b>スクール生感想内容一覧</b></h1>
  <div class="row">
    <div class="col-md-11 col-md-offset-0">
      <div style="margin-top: 50px;">
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-<%= message_type %>"><%= msg %></div>
        <% end %>
      </div>
      <br>
      <%= form_with method: :get, local: true do |f| %>
        <div class="year-month-day-label">
          <%= f.label :day, "年月検索" %>
        </div>
        <br>
        <div class="day-label">
          <%= f.date_select :day, {:discard_day => true, :include_blank => true, :start_year => Time.now.year, :end_year => Time.now.year-15}, class: "form-control" %>
          <%= f.submit "表示する", class: "btn btn-md btn-primary" %>
        </div>
      <% end %>
      <div class="student-search-label">
        <%= form_with(model: @user, method: :get, local: true) do |f| %>
          <%= f.label :search, "タイトル検索" %>
          <br>
          <div style="display: inline-flex">
            <%= f.text_field :name, class: "form-control", placeholder: "キーワードを入力" %>
            <%= f.submit "検索", class: "btn btn-md btn-primary btn-name-search" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="month-switching">
    <%= link_to "←", image_video_path(date: @first_day.prev_month), class: "btn btn-sm btn-primary" %>
    <span class="align-middle">&nbsp;&nbsp;&nbsp;<b><%= l(@first_day, format: :middle) %>&nbsp;&nbsp</b>
    <span class="align-top"><%= link_to "→", image_video_path(date: @first_day.next_month), class: "btn btn-sm btn-primary" %></span>
  </div>
  <div class="col-xs-6 col-md-6" style="margin-left: 380px; margin-top: 10px;">
    <% @image_videos.each do |image_video| %>
      <%= will_paginate %>
        <table class="table table-bordered table-condensed table-hover">
          <thead style="color: blue;">
            <tr>
              <th style="text-align: center;">撮影日</th>
              <th style="text-align: center;">タイトル</th>
              <th style="text-align: center;">お気に入り</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= image_video.photograph_day_on %></td>
              <td><%= link_to image_video.title, '#' %></td>
              <% if !Favorite.exists?(user_id: current_user.id, image_video_id: image_video.id) %>
                <td><%= button_to "追加", favorites_path(image_video), method: :post, class: "btn btn-primary btn-block" %></td>
              <% else %>
                <td><%= button_to "解除", favorite_path(image_video), method: :delete, class: "btn btn-primary btn-block" %></td>
              <% end %>
            </tr>
          </tbody>
      <%= will_paginate %>
    <% end %>
  </div>
</div>