config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'users#top_page'

  resources :users do
    member do
      get 'edit_user_info'
      patch 'update_user_info'
    end
  end

  resources :image_videos

  scope :api, { format: 'json' } do
    resources :image_videos do
      get :search, on: :collection
    end
  end

  resources :favorites

  get '/users' => redirect("users/sign_in")
  get '/users/password' => redirect("users/password/new")

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :image_videos, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :surf_spots, dependent: :destroy
  has_many :favorite_image_videos, through: :favorites, source: :favorite

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_TEL_REGEX = /\A\d{10,11}\z/

  validates :tel, presence: true, format: { with: VALID_TEL_REGEX }, length: { maximum: 11 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :birthday, presence: true
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # ユーザー名による絞り込み
  scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
  }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    super
  end

  # GET|POST /users/auth/twitter/callback
  def failure
    super
  end

  # protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    super(scope)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true


class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new(user_params)
  end

  # POST /resource
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録しました！"
      if current_user.admin
        redirect_to user_url
      else
        redirect_to new_user_session_url
      end
    else
      render 'new'
    end
  end

  # GET /resource/edit
  def edit
  end

  # PUT /resource
  def update
    @user.update_attributes(user_account_params)
    flash[:success] = "アカウント情報を更新しました"
    redirect_to root_url
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource``æ`«`‘`…`……`……………………/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_call, :tel, :email, :birthday, :using_surfboard, :admin, :password, :password_confirmation)
  end

  def user_account_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
    def after_sign_up_path_for(resource)
      super(resource)
    end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash[:danger] = "認証に失敗しました。"
      render :new
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_user_info, :update_user_info]

  def top_page
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(current_user.id)
  end

  def index
    @users = User.paginate(page: params[:page]).order(:id)
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
  end

  def edit_user_info
  end

  def update_user_info
    @user.update_attributes(user_params)
    flash[:success] = "#{@user.name}の基本情報を更新しました。"
    redirect_to users_url
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
end

private

  def user_params
    params.require(:user).permit(:tel, :email)
  end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/edit_user_info.html.erb
<% provide(:class_text, 'user-info') %>
<% provide(:button_text, '更新') %>
<div class="main-container-student-index">
  <div style="margin-top: 100px;">
    <h1 class="label-edit-title"><b>ユーザ情報編集</b></h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, url: update_user_info_user_path(@user), local: true, method: :patch) do |f| %>

          <%= f.label :tel, class: "label-#{yield(:class_text)}" %>
          <%= f.text_field :tel, placeholder: "半角数字、ハイフンなし", class: "form-control" %>

          <%= f.label :email, class: "label-#{yield(:class_text)}" %>
          <%= f.email_field :email, class: "form-control" %>

          <div class="center">
            <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            <%= link_to "キャンセル", users_path(current_user), class: "btn btn-default btn-cancell" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main-container-student-index">
  <div style="margin-top: 50px;">
    <% flash.each do |message_type, msg| %>
      <div class="alert alert-<%= message_type %>"><%= msg %></div>
    <% end %>
  </div>
  <div style="margin-top: 100px;">
    <h1 class="label-index"><b>スクール生一覧</b></h1>

    <div class="row">
      <div class="col-md-3 col-md-offset-8">
        <%= form_with(model: @user, method: :get, local: true) do |f| %>
          <%= f.label :search, "スクール生検索" %>
          <div style="display: inline-flex">
              <%= f.text_field :name, class: "form-control", placeholder: "キーワードを入力" %>
              <%= f.submit "検索", class: "btn btn-md btn-primary btn-name-search" %>
          </div>
        <% end %>
      </div>
      <div class="col-md-10 col-md-offset-1">
        <%= will_paginate %>
        <% if @users.count > 0 %>
          <table class="table table-bordered table-condensed table-hover" id="table-users">
            <thead>
              <tr>
                <th>ID</th>
                <th>名前</th>
                <th>電話番号</th>
                <th>メールアドレス</th>
                <th>スクール生情報操作</th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to user.name, user %></td>
                <td><%= user.tel %></td>
                <td><%= user.email %></td>
                <td>
                  <%= link_to "編集", edit_user_info_user_path(user), class: "btn btn-primary" %>
                  <div style="margin-top: -34px; margin-left: 60px;">
                  <%= button_to "削除", user, method: :delete,
                      data: { confirm: "削除してよろしいですか？" },
                      class: "btn btn-danger" %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        <% else %>
          <h3 class="center">スクール生が存在しません</h3>
        <% end %>
        <%= will_paginate %>
      </div>
    </div>
  </div>
<div>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <th>ID</th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th>名前</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @user.tel %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @user.email %></td>
    </tr>
  </table>
</div>

app/views/users/top_page.html.erb
<div class="main-container-manager">
  <div class="row">
    <div class="col-md-5 col-md-offset-5">
      <div style="margin-top: 50px;">
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-<%= message_type %>"><%= msg %></div>
        <% end %>
      </div>
      <h1 class="label-manager"><b>管理者専用ページ</b></h1>
      <br>
      <br>
      <%= form_with(model: @user, method: :get, local: true) do |f| %>

        <div class="admin-check-space">
          <h3>スクール生からの通知:なし</h3>
        </div>

        <div class="shop-space">
          <%= link_to "ショップ情報", '＃', class: "btn btn-primary btn-lg" %>
        </div>

        <div class="reservation-space">
          <%= link_to "スクール予約状況一覧", '＃', class: "btn btn-primary btn-lg" %>
        </div>

        <div class="student-impression-space">
          <%= link_to "スクール生動画・感想内容閲覧", image_videos_path, class: "btn btn-primary btn-lg" %>
        </div>

      <% end %>
    </div>
  </div>
</div>